# This is your mercury configuration file
# Below is an example config to get you started
# For more examples please look at the GIT repository
# https://github.com/schubergphilis/mercury/examples

[settings]
manage_network_interfaces = "yes"
enable_proxy = "yes"
[web]
binding = "localhost"
port = 9001
path = "tools/html"
[cluster.binding]
name = "localhost1"
addr = "127.0.0.1:9000"
authkey = "test"
[logging]
level = "debug"
output = "stdout"
[cluster.settings]
connection_retry_count = 3
connection_retry_interval = 10
connection_timeout = 10
ping_interval = 5
ping_timeout =  11
port = 9000
[dns]
binding = "0.0.0.0"
port = 53
allow_forwarding = [ "10.10.0.197/32", "::1/128" ]
[loadbalancer.settings]
default_balance_method = "roundrobin"
